---
title: "Otel Demonstration"
format: html
---

## Preparation

1.  Download and install Docker Desktop from: <https://www.docker.com/products/docker-desktop/>.

2.  In a terminal, pull and start a Jaeger container.

``` sh
docker run --rm --name jaeger \
 -p 16686:16686 \
 -p 4317:4317 \
 -p 4318:4318 \
 -p 5778:5778 \
 -p 9411:9411 \
 jaegertracing/jaeger:2.9.0
```

3. Docker Desktop will now show the running container with link to web UI at <http://localhost:16686>.

4. Add following line to `.Renviron` (may need sudo to modify).
This can't just be set within an R session as needs to apply to all new processes.

```sh
OTEL_TRACES_EXPORTER = "http"
```

5. In R, install mirai, dev promises, dev Shiny. **promises and shiny builds TBU**

```r
pak::pak(c("mirai", "rstudio/promises@bc1ca10", "rstudio/shiny@5e8e2ce"))
```

## Demonstration

1. Start up Jaeger in a terminal:

```sh
docker run --rm --name jaeger \
 -p 16686:16686 \
 -p 4317:4317 \
 -p 4318:4318 \
 -p 5778:5778 \
 -p 9411:9411 \
 jaegertracing/jaeger:2.9.0
```
2. Open web UI: <http://localhost:16686>

3. mirai-only example:

```r
library(mirai)
daemons(2)
mp <- mirai_map(1:3, rnorm)
m1 <- mirai(stop("error"))
m2 <- mirai(rlang::interrupt())
m3 <- mirai(Sys.sleep(2))
m3[]
daemons(0)
```

In web UI <http://localhost:16686> from the `Service` drop-down select `R`, click `Find Traces`.

Expected results:

- 3 `mirai::mirai` spans (2 show an error)
- 1 `mirai::mirai_map` span
- 1 `mirai::daemons` span
- 2 `mirai::daemon` spans

mirai otel vignette for interpretation: <https://mirai.r-lib.org/articles/v05-opentelemetry.html>

4. Shiny / mirai integrated example **Currently not working - to be updated**

Run any of the vignette demos at https://mirai.r-lib.org/articles/v02-promises.html, e.g.:

```r
library(shiny)
library(bslib)
library(mirai)

ui <- page_fluid(
  p("The time is ", textOutput("current_time", inline = TRUE)),
  hr(),
  numericInput("n", "Sample size (n)", 100),
  numericInput("delay", "Seconds to take for plot", 5),
  input_task_button("btn", "Plot uniform distribution"),
  plotOutput("plot")
)

server <- function(input, output, session) {
  output$current_time <- renderText({
    invalidateLater(1000)
    format(Sys.time(), "%H:%M:%S %p")
  })

  task <- ExtendedTask$new(
    function(...) mirai({Sys.sleep(y); runif(x)}, ...)
  ) |> bind_task_button("btn")

  observeEvent(input$btn, task$invoke(x = input$n, y = input$delay))

  output$plot <- renderPlot(hist(task$result()))

}

# run app using 1 local daemon
daemons(1)

# automatically shutdown daemons when app exits
onStop(function() daemons(0))

shinyApp(ui = ui, server = server)
```

Close app.

In web UI <http://localhost:16686> from the `Service` drop-down select `R`, click `Find Traces`.

